### ISSUE TITLE
Consuming a RESTful web service - Context Root Not Found

### ISSUE THREAD

**Issue by julianjupiter** [OpenLiberty/guide-rest-client-java#71] opened 2019-07-10 10:55 UTC
Following this tutorial, https://openliberty.io/guides/rest-client-java.html, I'm getting "Context Root Not Found" when hitting http://localhost:9080/artists and other endpoints.
![ol-consuming-rest](https://user-images.githubusercontent.com/15760709/60963750-355e8000-a344-11e9-8740-d790379bd443.PNG)

**Comment by yeekangc** [comment] 2019-07-10 13:08
@julianjupiter, can you clarify at which point you hit this error?

**Comment by julianjupiter** [comment] 2019-07-10 13:25
After copying the codes, I `cd` to `start` directory and issued the ff command:
`mvn liberty:start-server`

Console log displays no error but successful server start.

Hitting `http://localhost:9080/`, the OL welcome page is being displayed.

**Comment by justineechen** [comment] 2019-07-10 13:46
Hi @julianjupiter,

This may be occurring because you have another server running or that you may have to wait a couple of moments. Which OS are you using? If you are using a Mac could you try running `kill all -9 java` to kill any other servers that may be interfering?

**Comment by julianjupiter** [comment] 2019-07-10 14:01
> 
> 
> Hi @julianjupiter,
> 
> This may be occurring because you have another server running or that you may have to wait a couple of moments. Which OS are you using? If you are using a Mac could you try running `kill all -9 java` to kill any other servers that may be interfering? It could also be because you didn't run the install goal. So please ensure that you've ran `mvn install` to it's completion. Thanks!

I made sure no other instance of server is running.
![ol-server-stopped](https://user-images.githubusercontent.com/15760709/60974964-a2cada80-a35d-11e9-8430-b7669ce8b3b6.PNG)

I also ran `jps` command:
```
$ jps -m
2040
21240 Jps -m
```

After starting it again (`mvn liberty:start-server`):
```
$ jps -m
19328 jar --batch-file start defaultServer
2040
8028 Jps -m
```

I'm still getting the same error.

**Comment by yeekangc** [comment] 2019-07-10 14:07
I was able to reproduce i.e. hit the "Context Root Not Found" error when I ran "mvn liberty:start-server" only from scratch.  After I stopped the server and did "mvn install liberty:start-server", it worked.  Not sure if this is the case here but thought to note.

**Comment by gkwan-ibm** [comment] 2019-07-10 14:31
> After copying the codes, I `cd` to `start` directory and issued the ff commands:

Hi @julianjupiter,

As you said, may I understand what you did?

Based on the guide, did you try the "Starting the service" section? Without updating any code, you ran the command `mvn install liberty:start-server`. Did you sucessfully visit `http://localhost:9080/artists` and it returned as json string shown in the right pane?

Then, I assumed you 
- ran `mvn liberty:stop-server`
- created src/main/java/io/openliberty/guides/consumingrest/Consumer.java
- replaced src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java extractly as the right pane shown
- ran `mvn install`
- ran `mvn liberty:start-server`

Then, you visited `http://localhost:9080/artists` but only return the "Content Root Not Found"

Is it what you did?

**Comment by julianjupiter** [comment] 2019-07-10 15:09
I cloned again the repo and restarted my workstation. Doing again the steps in running the service, i's now working like a charm. My bad I don't know happened.

**Comment by gkwan-ibm** [comment] 2019-07-10 15:25
Thanks @julianjupiter

I am going to close this issue.

**Closed by gkwan-ibm** 2019-07-10 15:25 UTC
Labels: L3
